-- JourneyX — core intelligence pipeline schema (SoT §4.3).
--
-- Additive migration over 0001_init.sql. The physical table names from 0001
-- are kept (they carry the existing data and the whole query/UI layer):
--
--   customers  ≙ SoT `customer_profiles`
--   patterns   ≙ SoT `detected_patterns`
--   ingestion_log ≙ SoT replacement for `pipeline_metrics` (D-22)
--
-- New tables: resolution_logs, ingestion_log, notifications.
-- Dropped: journeys, identity_links, churn_signals — journeys and sessions are
-- computed at read time (SoT §4.7), identifier link metadata moves onto
-- customer_identifiers, and churn signals are patterns of type `churn_signal`
-- (SoT §4.8). Their contents are regenerated by `npm run seed`.

begin;

-- =========================================================================
-- events: producer idempotency, category, resolution outcome, raw payload
-- =========================================================================
alter table public.events
  add column if not exists source_event_id       text,
  add column if not exists dedup_key             text,
  add column if not exists event_category        text not null default 'unknown',
  add column if not exists identifiers           jsonb not null default '{}'::jsonb,
  add column if not exists resolution_method     text,
  add column if not exists resolution_confidence numeric(4,3),
  add column if not exists raw_data              jsonb;

-- Backfill before the NOT NULL/UNIQUE constraints land.
update public.events set dedup_key = id where dedup_key is null;

update public.events
   set event_category = coalesce(metadata->>'eventCategory', 'unknown')
 where event_category = 'unknown'
   and metadata ? 'eventCategory';

update public.events
   set resolution_method = case metadata->'resolution'->>'method'
                             when 'origin'        then 'new_profile'
                             when 'deterministic' then 'deterministic'
                             when 'probabilistic' then 'probabilistic'
                             when 'conflict'      then 'deterministic'
                             else 'new_profile'
                           end,
       resolution_confidence = coalesce(
         (metadata->'resolution'->>'confidence')::numeric, 1.000)
 where resolution_method is null;

alter table public.events
  alter column dedup_key set not null,
  alter column resolution_method set not null,
  alter column resolution_confidence set not null;

do $$ begin
  alter table public.events
    add constraint events_event_category_check
    check (event_category in ('browse','commerce','account','support','engagement','in_store','unknown'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.events
    add constraint events_resolution_method_check
    check (resolution_method in ('deterministic','probabilistic','new_profile'));
exception when duplicate_object then null; end $$;

create unique index if not exists uq_events_dedup_key on public.events(dedup_key);
create index if not exists idx_events_source_event_id on public.events(source_event_id);
create index if not exists idx_events_category on public.events(event_category);

-- Sessions and journeys are computed at read time (SoT §4.7), never stored.
alter table public.events drop column if exists journey_id;
alter table public.events drop column if exists session_id;

-- =========================================================================
-- customer_identifiers: link provenance moves off identity_links
-- =========================================================================
alter table public.customer_identifiers
  add column if not exists link_method     text,
  add column if not exists link_confidence numeric(4,3),
  add column if not exists last_seen_at    timestamptz;

do $$ begin
  if to_regclass('public.identity_links') is not null then
    update public.customer_identifiers ci
       set link_method     = coalesce(ci.link_method, il.link_method),
           link_confidence = coalesce(ci.link_confidence, il.confidence)
      from public.identity_links il
     where il.identifier_id = ci.id;
  end if;
end $$;

update public.customer_identifiers
   set link_method     = coalesce(link_method, 'deterministic'),
       link_confidence = coalesce(link_confidence, confidence, 1.000),
       last_seen_at    = coalesce(last_seen_at, first_seen_at)
 where link_method is null or link_confidence is null or last_seen_at is null;

alter table public.customer_identifiers
  alter column link_method set not null,
  alter column link_confidence set not null,
  alter column last_seen_at set not null;

do $$ begin
  alter table public.customer_identifiers
    add constraint customer_identifiers_link_method_check
    check (link_method in ('origin','deterministic','probabilistic','conflict'));
exception when duplicate_object then null; end $$;

-- One row per (profile, type, value): repeated sightings update last_seen_at.
delete from public.customer_identifiers a
 using public.customer_identifiers b
 where a.customer_id = b.customer_id
   and a.identifier_type = b.identifier_type
   and a.identifier_value = b.identifier_value
   and a.ctid > b.ctid;

create unique index if not exists uq_identifier_profile_type_value
  on public.customer_identifiers(customer_id, identifier_type, identifier_value);

-- A strong identifier belongs to exactly one profile; competing claims are
-- recorded as identity conflicts instead of silently merging (SoT §4.6).
delete from public.customer_identifiers a
 using public.customer_identifiers b
 where a.identifier_type in ('email','phone','loyalty_id')
   and a.identifier_type = b.identifier_type
   and a.identifier_value = b.identifier_value
   and a.customer_id <> b.customer_id
   and (a.first_seen_at, a.ctid) > (b.first_seen_at, b.ctid);

create unique index if not exists uq_strong_identifier
  on public.customer_identifiers(identifier_type, identifier_value)
  where identifier_type in ('email','phone','loyalty_id');

create index if not exists idx_identifiers_value_prefix
  on public.customer_identifiers(identifier_value text_pattern_ops);

-- =========================================================================
-- patterns (≙ detected_patterns): deterministic keys + event anchors
-- =========================================================================
alter table public.patterns
  add column if not exists pattern_key       text,
  add column if not exists event_id          text references public.events(id) on delete set null,
  add column if not exists related_event_ids text[] not null default '{}',
  add column if not exists evaluated_as_of   timestamptz,
  add column if not exists updated_at        timestamptz not null default now();

update public.patterns
   set pattern_key     = coalesce(pattern_key, pattern_type || ':legacy:' || id::text),
       evaluated_as_of = coalesce(evaluated_as_of, detected_at)
 where pattern_key is null or evaluated_as_of is null;

alter table public.patterns
  alter column pattern_key set not null,
  alter column evaluated_as_of set not null;

delete from public.patterns a
 using public.patterns b
 where a.customer_id = b.customer_id
   and a.pattern_key = b.pattern_key
   and a.ctid > b.ctid;

create unique index if not exists uq_pattern_profile_key
  on public.patterns(customer_id, pattern_key);
create index if not exists idx_patterns_event on public.patterns(event_id);
create index if not exists idx_patterns_detected_at on public.patterns(detected_at);

drop trigger if exists trg_patterns_updated on public.patterns;
create trigger trg_patterns_updated
  before update on public.patterns
  for each row execute function public.set_updated_at();

-- =========================================================================
-- customers (≙ customer_profiles): conflict flag + evaluation watermark
-- =========================================================================
alter table public.customers
  add column if not exists has_identity_conflict boolean not null default false,
  add column if not exists patterns_evaluated_at timestamptz;

update public.customers
   set has_identity_conflict = true
 where has_identity_conflict = false
   and coalesce((metadata->>'hasConflict')::boolean, false);

create index if not exists idx_customers_conflict
  on public.customers(has_identity_conflict) where has_identity_conflict;

-- =========================================================================
-- resolution_logs — the audit record behind every resolution decision
-- =========================================================================
create table if not exists public.resolution_logs (
    id                uuid primary key default gen_random_uuid(),
    event_id          text not null unique references public.events(id) on delete cascade,
    customer_id       text not null references public.customers(id) on delete cascade,
    method            text not null
                       check (method in ('deterministic','probabilistic','new_profile')),
    confidence        numeric(4,3) not null,
    evidence          jsonb not null default '[]'::jsonb,
    candidates        jsonb not null default '[]'::jsonb,
    identifiers_added jsonb not null default '[]'::jsonb,
    ambiguous         boolean not null default false,
    conflict          boolean not null default false,
    conflict_details  jsonb,
    algorithm_version text not null default 'v1',
    created_at        timestamptz not null default now()
);

create index if not exists idx_resolution_customer on public.resolution_logs(customer_id);
create index if not exists idx_resolution_method on public.resolution_logs(method);
create index if not exists idx_resolution_conflict on public.resolution_logs(conflict) where conflict;

-- =========================================================================
-- ingestion_log — one row per ingestion attempt (SoT D-22)
-- =========================================================================
create table if not exists public.ingestion_log (
    id            uuid primary key default gen_random_uuid(),
    received_at   timestamptz not null default now(),
    channel       text,
    event_type    text,
    outcome       text not null
                   check (outcome in ('accepted','duplicate','rejected','failed')),
    stage_reached text not null
                   check (stage_reached in ('parsed','validated','normalized','deduplicated','resolved','stored','patterns')),
    error_code    text,
    error_message text,
    event_id      text references public.events(id) on delete set null,
    latency_ms    integer,
    stage_timings jsonb not null default '{}'::jsonb
);

create index if not exists idx_ingestion_time on public.ingestion_log(received_at desc);
create index if not exists idx_ingestion_outcome on public.ingestion_log(outcome);

-- =========================================================================
-- notifications
-- =========================================================================
create table if not exists public.notifications (
    id                uuid primary key default gen_random_uuid(),
    notification_type text not null
                       check (notification_type in ('identity_conflict','churn_risk_high','unresolved_issue')),
    severity          text not null check (severity in ('info','warning','critical')),
    dedupe_key        text not null unique,
    title             text not null,
    message           text not null,
    customer_id       text references public.customers(id) on delete set null,
    deep_link         text,
    read              boolean not null default false,
    created_at        timestamptz not null default now()
);

create index if not exists idx_notifications_read on public.notifications(read, created_at desc);

-- =========================================================================
-- Superseded tables
-- =========================================================================
drop table if exists public.identity_links;
drop table if exists public.churn_signals;
drop table if exists public.journeys;

-- =========================================================================
-- RLS + grants for the new tables (reads only; writes need the service role)
-- =========================================================================
alter table public.resolution_logs enable row level security;
alter table public.ingestion_log   enable row level security;
alter table public.notifications   enable row level security;

do $policy$
declare t text;
begin
  foreach t in array array['resolution_logs','ingestion_log','notifications'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_read', t);
  end loop;
end
$policy$;

grant select on table
  public.resolution_logs,
  public.ingestion_log,
  public.notifications
to anon, authenticated;

-- The pipeline and the seeder write with the service-role key. This project
-- does not rely on default privileges (see 0002), so grant writes explicitly.
grant select, insert, update, delete on table
  public.customers,
  public.customer_identifiers,
  public.events,
  public.patterns,
  public.resolution_logs,
  public.ingestion_log,
  public.notifications
to service_role;

commit;

-- PostgREST caches the schema; without a reload the new columns and tables
-- answer `42703` / `PGRST205` until the cache refreshes on its own.
notify pgrst, 'reload schema';
